spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment?serverTimezone=Asia/Seoul&useSSL=false
    username: suhwan
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
pg:
  url: https://ecf786e3-8d6a-4c12-bf43-65507c2abaa3.mock.pstmn.io/confirm
